spring:
  application:
    name: Expense Manager

  data:
    mongodb:
      uri: ${MONGODB_URI}

  main:
    allow-circular-references: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://authorization-server-50019167766.catalystappsail.in

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        security: trace

mail:
  google:
    appPassword: ${FAMILY_EXPENSE_MANAGER_APP_PASSWORD}
    email: ${FAMILY_EXPENSE_MANAGER_EMAIL_ID}
