spring:
  application:
    name: Expense Manager

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

logging:
  level:
    org:
      springframework:
        security: trace
